# Automatically generated by pb2py
# fmt: off
import protobuf as p


class DashSignProUpRegTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 752

    def __init__(
        self,
        outputs_count: int = None,
        inputs_count: int = None,
        coin_name: str = None,
        lock_time: int = None,
        payload_version: int = None,
        protx_hash: bytes = None,
        mn_mode: int = None,
        pub_key_operator: bytes = None,
        key_id_voting: bytes = None,
        operator_reward: int = None,
        script_payout: bytes = None,
        payload_sig: bytes = None,
    ) -> None:
        self.outputs_count = outputs_count
        self.inputs_count = inputs_count
        self.coin_name = coin_name
        self.lock_time = lock_time
        self.payload_version = payload_version
        self.protx_hash = protx_hash
        self.mn_mode = mn_mode
        self.pub_key_operator = pub_key_operator
        self.key_id_voting = key_id_voting
        self.operator_reward = operator_reward
        self.script_payout = script_payout
        self.payload_sig = payload_sig

    @classmethod
    def get_fields(cls):
        return {
            1: ('outputs_count', p.UVarintType, 0),  # required
            2: ('inputs_count', p.UVarintType, 0),  # required
            3: ('coin_name', p.UnicodeType, 0),  # default=Dash
            4: ('lock_time', p.UVarintType, 0),  # default=0
            5: ('payload_version', p.UVarintType, 0),  # default=1
            6: ('protx_hash', p.BytesType, 0),
            7: ('mn_mode', p.UVarintType, 0),  # default=0
            8: ('pub_key_operator', p.BytesType, 0),
            9: ('key_id_voting', p.BytesType, 0),
            10: ('operator_reward', p.UVarintType, 0),
            11: ('script_payout', p.BytesType, 0),
            12: ('payload_sig', p.BytesType, 0),
        }
